name: PR_CHECKER

on:
  pull_request:
    types: [opened, reopened]

jobs:
  models_checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python Env
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r scripts/requirements.txt
    - name: Check
      run: |
        git fetch
        python scripts/checker/check.py
    - name: Post push
      uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          force: false
          branch: ${{ github.event.pull_request.head.ref }}
  