name: PR_CHECKER

on:
  pull_request:
    types: [opened, reopened]

jobs:
  models_checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python Env
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r scripts/requirements.txt
    - name: Check
      run: |
        git fetch
        python scripts/checker/check.py
    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        add: 'datasets'
        message: 'unreference vertices removed'
        commit: --allow-empty
        fetch: true
        push: ${{ github.ref_name }}